name: Trigger auto deployment for alopecia

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/alopecia-AutoDeployTrigger-9dad2aa6-b782-43b2-97c2-d90c5795fe0b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: mrc.microsoft.com
          username: ${{ secrets.ALOPECIA_REGISTRY_USERNAME }}
          password: ${{ secrets.ALOPECIA_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mrc.microsoft.com/alopecia:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALOPECIA_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n alopecia -g Alopecia --server mrc.microsoft.com --username  ${{ secrets.ALOPECIA_REGISTRY_USERNAME }} --password ${{ secrets.ALOPECIA_REGISTRY_PASSWORD }}
            az containerapp update -n alopecia -g Alopecia --image mrc.microsoft.com/alopecia:${{ github.sha }}
